config/routes.rb
Rails.application.routes.draw do
  resources :private_messages
  resources :rooms
  resources :messages
  get 'sessions/new'
  get 'static_pages/home'
  root 'static_pages#home'
    get '/signup', to: 'users#new'    
  resources :users, except: [:new]  
   get    '/login',  to: 'sessions#new'    
  post   '/login',  to: 'sessions#create'    
  get    '/logout', to: 'sessions#destroy' 
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  has_many :messages
  has_many :private_messages
    validates_presence_of :firstname
    validates_length_of :firstname, maximum: 70
  validates_presence_of :lastname
  validates_length_of :lastname, maximum: 70
    before_save { self.email = email.downcase }    
    validates_presence_of :email
    validates_length_of :email, maximum: 255    
    validates_uniqueness_of :email, case_sensitive: false    
    validates_format_of :email, with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i 
  has_secure_password
  validates_presence_of :password
validates_length_of :password, minimum: 5

  def fullname
    return "#{firstname} #{lastname}"
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_login, except: [:new, :create]
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :authorized_to_modify_and_destroy, only: [:edit, :update, :destroy]

  def authorized_to_modify_and_destroy
   if current_user != @user
      redirect_to users_url, notice: "You can only edit or delete your own account."
   end
end
  
  # GET /users
  def index
    @users = User.all
  end

  # GET /users/1
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
 def create
    @user = User.new(user_params)

    if @user.save
      log_in @user    
      redirect_to root_url, notice: 'Account created and logged in.'
    else
      render :new
    end
  end

  # PATCH/PUT /users/1
  def update
    if @user.update(user_params)
      redirect_to @user, notice: 'User was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /users/1
   def destroy
    if @user == current_user
        log_out
    end
    @user.destroy
    redirect_to users_url, notice: 'User was successfully destroyed.'
  end
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
def user_params
   params.require(:user).permit(:firstname,:lastname, :email, :password,
                                :password_confirmation)
end  
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<!DOCTYPE html>
<html>
<style>
</style>

<%= form_with(model: user) do |form| %>
  <% if user.errors.any? %>
    <div style="color: red" id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :firstname %>
    <%= form.text_field :firstname %>
  </div>

  <div class="field">
    <%= form.label :lastname %>
    <%= form.text_field :lastname %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>
  <div class="field">
    <%= form.label :password %>
    <%= form.password_field :password %>
  </div>

  <div class="field">
    <%= form.label :password_confirmation %>
    <%= form.password_field :password_confirmation %>
  </div>
  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

</html>

app/views/users/edit.html.erb
<h1>Editing User Account</h1>
<%= render 'form', user: @user %>
<%= link_to 'Home', root_path %>

app/views/users/index.html.erb
<h1 style="text-align: center; font-family: 'Georgia'">Direct Message</h1>
<h3 style="text-align: center; font-family: 'Century Gothic'">If you would like to chat with someone privately you can use direct messages!</h3>
<body>
<table align="center">
  <tr>
    <th>Member List:</th>

  </tr>
  <tbody >
  <% @users.each do |user| %>
    <tr>
      <td><%= link_to user.fullname, user %></td>
      <td><%= link_to "Send a Message", new_private_message_path(:private_message =>{:recipient_id => user.id})%></td>
      </td>
    </tr>
  <% end %>
  </tbody>
</table>
<div align="left"><%= image_tag "direct_message.svg" %></div>
</body>

app/views/users/new.html.erb
<h1>Create New Account</h1>
<%= link_to 'Back', root_path %>
<%= render 'form', user: @user %>

app/views/users/show.html.erb
<h1 style="font-family: 'Georgia'">User Profile</h1>
<p>
  <strong>Name:</strong>
  <%= @user.fullname %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<%= link_to 'Home', root_path %> |
<%= link_to 'Message', new_private_message_path(:private_message =>{:recipient_id => @user.id}) %>