config/routes.rb
Rails.application.routes.draw do
  resources :private_messages
  resources :rooms
  resources :messages
  get 'sessions/new'
  get 'static_pages/home'
  root 'static_pages#home'
    get '/signup', to: 'users#new'    
  resources :users, except: [:new]  
   get    '/login',  to: 'sessions#new'    
  post   '/login',  to: 'sessions#create'    
  get    '/logout', to: 'sessions#destroy' 
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/Shared/_navigation_bar.html.erb
<head>
  <style>
      ul {
          list-style-type: none;
          margin: 0;
          padding: 0;
          overflow: hidden;
          background-color: #333;
      }

      li {
          float: left;/*
          border-right:1px solid #bbb;*/
      }

      li:last-child {
          border-right: none;
      }

      li a {
          display: block;
          color: white;
          text-align: center;
          padding: 14px 16px;
          text-decoration: none;
      }

      li a:hover:not(.active) {
          background-color: #111;
      }

      .active {
          background-color: #04AA6D;
      }

      .avatar {
          width:40px;
      }
      body {
          background-color: lightblue;
      }
  </style>

</head>
<% if logged_in? %>
<ul>
  <li><%= link_to "Chatify" , static_pages_home_path %></li>
  <li><%= link_to "Rooms" , rooms_path %></li>
  <li><%= link_to "Members" , users_path %></li>
  <li><%= link_to "Sign Out" , logout_path %></li>

    <img class="avatar" src="<%= gravatar_url(current_user) %>">
      <a style="color: white; "> <%= current_user.email %>
      </a>

</ul>

<% end %>