config/routes.rb
Rails.application.routes.draw do
  resources :private_messages
  resources :rooms
  resources :messages
  get 'sessions/new'
  get 'static_pages/home'
  root 'static_pages#home'
    get '/signup', to: 'users#new'    
  resources :users, except: [:new]  
   get    '/login',  to: 'sessions#new'    
  post   '/login',  to: 'sessions#create'    
  get    '/logout', to: 'sessions#destroy' 
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/room.rb
class Room < ApplicationRecord
  has_many :messages, dependent: :destroy,
           inverse_of: :room
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :load_entities

  def index
    @rooms = Room.all
  end

  def new
    @room = Room.new
  end

  def create
    @room = Room.new permitted_parameters

    if @room.save
      flash[:success] = "Room #{@room.name} was created successfully"
      redirect_to rooms_path
    else
      render :new
    end
  end

  def edit
  end
  def show
    @message = Message.new room:@room
    @messages = @room.messages.includes(:user)
  end

  def update
    if @room.update_attributes(permitted_parameters)
      flash[:success] = "Room #{@room.name} was updated successfully"
      redirect_to rooms_path
    else
      render :new
    end
  end

  protected

  def load_entities
    @rooms = Room.all
    @room = Room.find(params[:id]) if params[:id]
  end

  def permitted_parameters
    params.require(:room).permit(:name)
  end
  end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/rooms/_form.html.erb
<%= simple_form_for @room do |form| %>
  <%= form.input :name %>
  <%= form.submit "Save", class: 'btn btn-success' %>
<% end %>

app/views/rooms/_rooms.html.erb
<!DOCTYPE html>
<html lang="en">
<head>

  <style>
      body {
          margin: 0;
      }
      ul.b {
          list-style-type: square;
          background-color: teal;
      }

      .column {
          float: left;
          padding: 0px;
          text-align: center;
      }
      .column.side {
          width: 10%;

      }



  </style>
</head>



<body >

<div class ="column side",>
  <b style="font-size: large;font-family: 'Century Gothic'"><%= link_to "CREATE A NEW ROOM", new_room_path %></b>
<p> </p>
  <ul class="b">
<% if @rooms.present? %>
      <li style="color: white";><%= "Available Rooms:" %></li>
    <% @rooms.each do |room| %>

     <li> <%= link_to room.name, room_path(room) %></li>

    <% end %>
    </ul>
  </div>
<% else %>
  <div style="color: white; text-align: center"; >
     No rooms created yet!
  </div>
<% end %>
</body>

app/views/rooms/edit.html.erb
<h1>
  Editing room <%= @room.name %>
</h1>

<%= render partial: 'form' %>

app/views/rooms/index.html.erb
<html>
<head>
  <style>
      body {
          background: powderblue ;
      }
  </style>
</head>
<body>



  <h1 style="text-align: center; font-family: 'Georgia'"> Let's Chat!</h1>

  <h2 style="text-align: center; font-family: 'Century Gothic'">
  You can create or join a room from the sidebar.
</h2>
  <div style="padding-left: 20px">
    <%= render partial: 'rooms' %>
  </div>
      <div align="right"><%= image_tag "network.svg" %></div>
</body>
</html>

app/views/rooms/new.html.erb
<h1 style="text-align: center; font-family: 'Georgia'">
  CREATE A ROOM!
</h1>
<div align="center">
<%= render partial: 'form' %>
</div>

app/views/rooms/show.html.erb
<!DOCTYPE html>
<html>
<head>
  <style>
      body {
          margin: 0 auto;
          max-width: 800px;
          padding: 0 20px;
      }

      .container {
          border: 2px solid #dedede;
          background-color: #f1f1f1;
          border-radius: 5px;
          padding: 10px;
          margin: 10px 0;
      }

      .darker {
          border-color: #ccc;
          background-color: #ddd;
      }

      .container::after {
          content: "";
          clear: both;
          display: table;
      }

      .container img {
          float: left;
          max-width: 60px;
          width: 100%;
          margin-right: 20px;
          border-radius: 50%;
      }

      .container img.right {
          float: right;
          margin-left: 20px;
          margin-right:0;
      }

      .time-right {
          float: right;
          color: #aaa;
      }

      .time-left {
          float: left;
          color: #999;
      }



      .browser {
          background: white;
      }

      .browser > h2, p {
          margin: 4px;
          font-size: 90%;
      }

      footer {
          text-align: center;
          padding: 3px;
          background-color: teal;
          color: white;
      }
      div.ex3 {
          background-color:white;
          width: 790px;
          height: 310px;
          overflow: auto;
      }
  </style>
</head>
<body>
<div>

<h1 style="text-align: center; font-family: 'Georgia'">
  <%= @room.name %>
</h1>


<div class="row">
<div class="ex3">
      <% @messages.each do |room_message| %>
        <% if room_message.user == current_user %>
            <div class="container">
             <p style="text-align: right"> <%= room_message.user.fullname %></p>
              <p style="text-align: right"><%= room_message.chattext %></p>
              <span class="time-right"><%= room_message.created_at %></span>
            </div>
       <%else %>
          <div class="container darker">
          <%= room_message.user.fullname %>
          <p><%= room_message.chattext %></p>
          <span class="time-left"><%= room_message.created_at %></span>
        </div>
        <%end %>

      <% end %>
    </div>

  <%= simple_form_for @message, remote: true do |form| %>
    <div class="input-group mb-3">
      <%= form.input :chattext, as: :string,
                     wrapper: false,
                     label: false,
                     input_html: {
                       class: 'chat-input',
                       autocomplete: 'off'
                     } %>
      <div class="input-group-append">
        <%= form.submit "Send", class: 'btn btn-primary chat-input' %>
      </div>
    </div>

    <%= form.input :room_id, as: :hidden %>
  <% end %>
  </div>
</div>
  </body>
</html>